// Generated by scripts/generate-contract.ts. Do not edit.

export const CONTRACT_VERSION = 0;

export const STATUS = {
  "success": 0,
  "endOfInput": 1,
  "inputFailure": 2,
  "outputFailure": 3,
  "storageFailure": 4,
  "invalid": 254,
} as const;

export const BYTE_GATEWAY_PROFILE = {
  "id": 1,
  "version": 0,
  "operations": {
    "readInputByte": 0,
    "writeOutputByte": 1,
    "readStorageByte": 2,
    "rewindStorageInput": 3,
    "writeStorageByte": 4,
    "seekStorageOutput": 5,
  },
} as const;
