interface Contract {
  readonly contractVersion: number;
  readonly status: Readonly<Record<string, number>>;
  readonly profiles: Readonly<
    Record<string, {
      readonly id: number;
      readonly version: number;
      readonly operations: Readonly<Record<string, number>>;
    }>
  >;
}

const contractUrl = new URL(
  "../contracts/z80-services-v0.json",
  import.meta.url,
);
const tsUrl = new URL("../reference/contract.ts", import.meta.url);
const atomUrl = new URL(
  "../native/include/z80-services-v0.asmi",
  import.meta.url,
);
const check = Deno.args.includes("--check");

const contract = JSON.parse(await Deno.readTextFile(contractUrl)) as Contract;

function assertByte(name: string, value: number): void {
  if (!Number.isInteger(value) || value < 0 || value > 0xff) {
    throw new Error(`${name} must be a byte`);
  }
}

function constantName(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function typescriptObject(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/([0-9"]|})\n/g, "$1,\n");
}

assertByte("contractVersion", contract.contractVersion);
for (const [name, value] of Object.entries(contract.status)) {
  assertByte(`status.${name}`, value);
}
for (const [name, profile] of Object.entries(contract.profiles)) {
  assertByte(`profiles.${name}.id`, profile.id);
  assertByte(`profiles.${name}.version`, profile.version);
  for (const [operation, value] of Object.entries(profile.operations)) {
    assertByte(`profiles.${name}.operations.${operation}`, value);
  }
}

const ts = `// Generated by scripts/generate-contract.ts. Do not edit.\n\n` +
  `export const CONTRACT_VERSION = ${contract.contractVersion};\n\n` +
  `export const STATUS = ${typescriptObject(contract.status)} as const;\n\n` +
  Object.entries(contract.profiles).map(([name, profile]) =>
    `export const ${constantName(name)}_PROFILE = ${
      typescriptObject(profile)
    } as const;\n`
  ).join("\n");

const atomLines = [
  "; Generated by scripts/generate-contract.ts. Do not edit.",
  "; Experimental Z80 Services contract 0.",
  "",
  `ZS_CONTRACT EQU ${contract.contractVersion}`,
];
for (const [name, value] of Object.entries(contract.status)) {
  atomLines.push(`ZS_STATUS_${constantName(name)} EQU ${value}`);
}
for (const [name, profile] of Object.entries(contract.profiles)) {
  const prefix = `ZS_${constantName(name)}`;
  atomLines.push(`${prefix}_PROFILE EQU ${profile.id}`);
  atomLines.push(`${prefix}_VERSION EQU ${profile.version}`);
  for (const [operation, value] of Object.entries(profile.operations)) {
    atomLines.push(`${prefix}_${constantName(operation)} EQU ${value}`);
  }
}
const atom = `${atomLines.join("\n")}\n`;

async function update(url: URL, expected: string): Promise<void> {
  if (check) {
    const actual = await Deno.readTextFile(url);
    if (actual !== expected) {
      throw new Error(`${url.pathname} is not generated from the contract`);
    }
    return;
  }
  await Deno.writeTextFile(url, expected);
}

await update(tsUrl, ts);
await update(atomUrl, atom);
