interface Assignment {
  readonly code: number;
  readonly atom: string;
}

interface Profile {
  readonly id: number;
  readonly version: number;
  readonly atomId: string;
  readonly atomVersion: string;
  readonly operations: Readonly<Record<string, Assignment>>;
}

interface Contract {
  readonly contractVersion: number;
  readonly status: Readonly<Record<string, Assignment>>;
  readonly profiles: Readonly<Record<string, Profile>>;
}

const contractUrl = new URL(
  "../contracts/z80-services-v0.json",
  import.meta.url,
);
const tsUrl = new URL("../reference/contract.ts", import.meta.url);
const atomUrl = new URL(
  "../native/include/z80-services-v0.asmi",
  import.meta.url,
);
const check = Deno.args.includes("--check");

const contract = JSON.parse(await Deno.readTextFile(contractUrl)) as Contract;

function assertByte(name: string, value: number): void {
  if (!Number.isInteger(value) || value < 0 || value > 0xff) {
    throw new Error(`${name} must be a byte`);
  }
}

function assertAtomSymbol(name: string, value: string): void {
  if (!/^[A-Z][A-Z0-9_]{0,7}$/.test(value)) {
    throw new Error(
      `${name} must be an ATOM symbol of at most eight characters`,
    );
  }
}

function constantName(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function typescriptObject(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/([0-9"]|})\n/g, "$1,\n");
}

function codes(
  assignments: Readonly<Record<string, Assignment>>,
): Record<string, number> {
  return Object.fromEntries(
    Object.entries(assignments).map(([name, assignment]) => [
      name,
      assignment.code,
    ]),
  );
}

function validateAssignments(
  path: string,
  assignments: Readonly<Record<string, Assignment>>,
  atomSymbols: Set<string>,
): void {
  const numericCodes = new Set<number>();
  for (const [name, assignment] of Object.entries(assignments)) {
    assertByte(`${path}.${name}.code`, assignment.code);
    assertAtomSymbol(`${path}.${name}.atom`, assignment.atom);
    if (numericCodes.has(assignment.code)) {
      throw new Error(`${path} repeats code ${assignment.code}`);
    }
    if (atomSymbols.has(assignment.atom)) {
      throw new Error(`ATOM symbol ${assignment.atom} is repeated`);
    }
    numericCodes.add(assignment.code);
    atomSymbols.add(assignment.atom);
  }
}

assertByte("contractVersion", contract.contractVersion);
const atomSymbols = new Set<string>();
validateAssignments("status", contract.status, atomSymbols);
for (const [name, profile] of Object.entries(contract.profiles)) {
  assertByte(`profiles.${name}.id`, profile.id);
  assertByte(`profiles.${name}.version`, profile.version);
  assertAtomSymbol(`profiles.${name}.atomId`, profile.atomId);
  assertAtomSymbol(`profiles.${name}.atomVersion`, profile.atomVersion);
  for (const symbol of [profile.atomId, profile.atomVersion]) {
    if (atomSymbols.has(symbol)) {
      throw new Error(`ATOM symbol ${symbol} is repeated`);
    }
    atomSymbols.add(symbol);
  }
  validateAssignments(
    `profiles.${name}.operations`,
    profile.operations,
    atomSymbols,
  );
}

const ts = `// Generated by scripts/generate-contract.ts. Do not edit.\n\n` +
  `export const CONTRACT_VERSION = ${contract.contractVersion};\n\n` +
  `export const STATUS = ${
    typescriptObject(codes(contract.status))
  } as const;\n\n` +
  Object.entries(contract.profiles).map(([name, profile]) =>
    `export const ${constantName(name)}_PROFILE = ${
      typescriptObject({
        id: profile.id,
        version: profile.version,
        operations: codes(profile.operations),
      })
    } as const;\n`
  ).join("\n");

const atomLines = [
  "; Generated by scripts/generate-contract.ts. Do not edit.",
  "; Experimental Z80 Services contract 0.",
  "",
  `ZS_CONT EQU ${contract.contractVersion}`,
];
for (const assignment of Object.values(contract.status)) {
  atomLines.push(`${assignment.atom} EQU ${assignment.code}`);
}
for (const profile of Object.values(contract.profiles)) {
  atomLines.push(`${profile.atomId} EQU ${profile.id}`);
  atomLines.push(`${profile.atomVersion} EQU ${profile.version}`);
  for (const assignment of Object.values(profile.operations)) {
    atomLines.push(`${assignment.atom} EQU ${assignment.code}`);
  }
}
const atom = `${atomLines.join("\n")}\n`;

async function update(url: URL, expected: string): Promise<void> {
  if (check) {
    const actual = await Deno.readTextFile(url);
    if (actual !== expected) {
      throw new Error(`${url.pathname} is not generated from the contract`);
    }
    return;
  }
  await Deno.writeTextFile(url, expected);
}

await update(tsUrl, ts);
await update(atomUrl, atom);
